delhome:
  messages:
    success: "&aHome has been successfully removed."
    fail: "&eYou don't have home."

home:
  messages:
    title: "&aTeleportation"
    subtitle: "&fTime left: "
    success: "&aYou have been teleported successfully."
    cancel: "&eYou moved, teleportation cancelled!"
    fail: "&eYou don't have home."
  options:
    delay: 5
    sound: true
    effect: true

sethome:
  messages:
    success: "&aHome has been set to your location."
    fail: "&eYou already have home."
