main: org.dziedzic44.Homes.Main
name: Homes
version: 1.1
author: dziedzic44
description: Homes is lightweight plugin which allow players to create, teleport and delete their own warps called homes.

commands:
  delhome:
    usage: /delhome
    description: Deletes home.
  home:
    usage: /home
    description: Teleports to home.
  sethome:
    usage: /sethome
    description: Sets home.
