name: Homes
main: org.dziedzic44.Homes.Main
description: Homes is lightweight plugin which allow players to create, teleport and delete their own warp called homes.
author: dziedzic44
version: 1.0

commands:
  delhome:
    usage: /delhome
    description: Deletes home.
  home:
    usage: /home
    description: Teleports to home.
  sethome:
    usage: /sethome
    description: Sets home.
